export const sliderItems = [
  {
    id: 1,
    img: "https://m.media-amazon.com/images/I/71IfKmKffPL._UL1500_.jpg",
    title: "Men's T-Shirts",
    desc: "100% Cotton, 0% Polyester.Cool Fabric, suitable for Summer Season",
    bg: "f0f0f0",
  },
  {
    id: 2,
    img: "https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/81Hl0rZTgcL._UL1500_.jpg",
    title: "Women's T-Shirts",
    desc: "100% Cotton, 0% Polyester.Cool Fabric, suitable for All Season",
    bg: "fbf0f4",
  },
  {
    id: 3,
    img: "https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/715YTbR0hgL._UL1500_.jpg",
    title: "Kids T-Shirts",
    desc: "100% Cotton, 0% Polyester, Graphic Printed Design. Cool Fabric, suitable for all Season",
    bg: "f0f0f0",
  },
  {
      id: 4,
      img: "https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/61ge3BpXVES._UL1000_.jpg",
      title: "Unisex Accessories",
      desc: "Unisex Accessories. Suitable for Semi-Casuals and Casual wears",
      bg: "fbf0f4",
    },
];

export const data = {
    products: [
      {
        name: "Dennis Lingo Men's Shirt",
        sku: 'DLMS001',
        department: 'men',
        category: 'Shirts',
        image: 'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/61KNBTw4K8S._UL1500_.jpg',
        price: <i class="fa fa-inr">649</i>,
        countInStock: 10,
        brand: 'Dennis Lingo',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality shirt',
      },
      {
        name: "Dennis Lingo Men's Shirt",
        sku: 'DLMS002',
        department: 'men',
        category: 'Shirts',
        image: 'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/71Bo9OtlEtL._UL1440_.jpg',
        price: <i class="fa fa-inr">749</i>,
        countInStock: 10,
        brand: 'Dennis Lingo',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality shirt',
      },
      {
        name: "Allen Solly Men's T-Shirt",
        sku: 'DLMS003',
        department: 'men',
        category: 'T-Shirts',
        image: 'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/71eUwDk8z+L._UL1500_.jpg',
        price: <i class="fa fa-inr">499</i>,
        countInStock: 10,
        brand: 'Allen Solly',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality t-shirt',
      },
      {
        name: "Urbano Fashion Men's T-Shirt",
        sku: 'DLMS004',
        department: 'men',
        category: 'T-Shirts',
        image: 'https://m.media-amazon.com/images/I/71IfKmKffPL._UL1500_.jpg',
        price: <i class="fa fa-inr">499</i>,
        countInStock: 10,
        brand: 'Urbano Fashion',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality t-shirt',
      },
      {
        name: "SHAUN Women T-Shirt",
        sku: 'DLMS005',
        department: 'women',
        category: 'T-Shirts',
        image: 'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/81Hl0rZTgcL._UL1500_.jpg',
        price: <i class="fa fa-inr">384</i>,
        countInStock: 10,
        brand: 'SHAUN',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality t-shirt',
      },
      {
        name: "JuneBerry Cotton Women's T-Shirt",
        sku: 'DLMS006',
        department: 'women',
        category: 'T-Shirts',
        image: 'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/6118pP1y20L._UL1020_.jpg',
        price: <i class="fa fa-inr">412</i>,
        countInStock: 10,
        brand: 'JuneBerry',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality t-shirt',
      },
      {
        name: "Googogaaga Cotton kids T-Shirt",
        sku: 'DLMS007',
        department: 'boys',
        category: 'T-Shirts',
        image: 'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/51-WSZn6qEL.jpg',
        price: <i class="fa fa-inr">378</i>,
        countInStock: 10,
        brand: 'Googogaaga',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality t-shirt',
      },{
        name: "Bon Organik Cotton Kids T-Shirt",
        sku: 'DLMS008',
        department: 'boys',
        category: 'T-Shirts',
        image: 'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/715YTbR0hgL._UL1500_.jpg',
        price: <i class="fa fa-inr">499</i>,
        countInStock: 10,
        brand: 'Bon Organik',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality t-shirt',
      },
      {
        name: "University Trendz Bracelet",
        sku: 'DLMS009',
        department: 'unisex',
        category: 'Accessories',
        image: 'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/61ge3BpXVES._UL1000_.jpg',
        price: <i class="fa fa-inr">214</i>,
        countInStock: 10,
        brand: 'University Trendz',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality t-shirt',
      },{
        name: "WildHorn Brown Leather Men's wallet",
        sku: 'DLMS010',
        department: 'men',
        category: 'Accessories',
        image: 'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/91wTVAS+-uL._SL1500_.jpg',
        price: <i class="fa fa-inr">379</i>,
        countInStock: 10,
        brand: 'WildHorn',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality t-shirt',
      }
    ]
  };
